### ISSUE TITLE
你好，我在运行web.py的时候，链接打开的同时报错，这该怎么解决？（并且我已确认代理正常，gradio版本是3.31.0，api key正常）

### ISSUE THREAD

**Issue by abandonnnnn** [zhaozh10/ChatCAD#6]
(cad) zzz@zzz:~/yz/AllVscodes/ChatCAD-main$ python3 web.py
/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/revChatGPT/__init__.py:29: UserWarning: The current Python is not a recommended version, 3.10+ is recommended
  __import__("warnings").warn(
Running on local URL:  http://127.0.0.1:4900

To create a public link, set `share=True` in `launch()`.
**ERROR:    Exception in ASGI application**
Traceback (most recent call last):
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/gradio/routes.py", line 263, in api_info
    return gradio.blocks.get_api_info(config, serialize)  # type: ignore
  File "/home/zzz/anaconda3/envs/cad/lib/python3.9/site-packages/gradio/blocks.py", line 504, in get_api_info
    serializer = serializing.COMPONENT_MAPPING[type]()
KeyError: 'dataset'

**Comment by JuneCly** [comment]
您好，我也遇到了同样的问题，请问您现在解决了吗？

**Comment by abandonnnnn** [comment]
我用的是linux系统，输入这个解决了。如果你使用的也是linux，
1.在设置里更改我的网络代理，如下图
![批注 2023-12-05 125727](https://github.com/zhaozh10/ChatCAD/assets/97727907/689f1f61-708e-4b83-93bb-c5d8f5d8c8a1)

2.在终端里输入这行命令（注意引号要输入英文的）：
export https_proxy=“http://127.0.0.1:7890”

然后就可以了，但是有时候回答的字数太长会失败.......
说一个我的题外话：很头疼，我自己用简短代码测试简单问题的时候是可以调用的，key也是正常的，但是一放进chatcad的网页就说我的key'不正确,,,,,,,如果你也遇到这个问题的话，欢迎你与我沟通！！！

**Comment by 2279915269** [comment]
你好，我也遇到了api key错误的问题，请问应该如何解决呢？

**Comment by zhaozh10** [comment]
> 你好，我也遇到了api key错误的问题，请问应该如何解决呢？

如还是无法解决，请考虑将ChatGPT替换为LLaMA2-13B

**Comment by 2279915269** [comment]
您能详细讲解一下需要更改哪个文件吗，谢谢您

**Comment by zhaozh10** [comment]
> 您能详细讲解一下需要更改哪个文件吗，谢谢您

chat_bot.py中self.agent是一个chatgpt对象，其需要具有“重置状态”的self.agent.reset()和“回答问题并记忆问答历史的”self.agent.ask()的方法，可以将
self.agent = Chatbot(engine=self.engine,api_key=self.api_key,system_prompt=system_prompt,proxy="127.0.0.1:7890")
内容改为初始化一个LLaMA或Mistral（见huggingface），并进行适当修改为其添加reset()和ask()的功能

**Comment by zoujing925** [comment]
@abandonnnnn 你好，我也遇到了和你同样的问题，链接打开的同时报错，根据你的回答设置代理还是报错，请问还有什么办法可以解决
